spring: 
  profiles: 
    active: dev

---
server: 
  port: 8001

spring: 
  profiles: dev
  application: 
    name: microservicecloud-config-dept-client
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01?serverTimezone=UTC
    username: root
    password: 123456

mybatis: 
  mapper-locations: classpath:mybatis/mapper/*.xml  
  type-aliases-package: com.wonders.springcloud.pojo  
  config-location: classpath:mybatis/mybatis.cfg.xml

#客户端注册进eureka服务列表内
eureka:
  client:
    service-url: 
      #defaultZone: http://localhost:6001/eureka
      #入驻多个集群
      defaultZone: http://eureka7001.com:7001/eureka/
  instance: 
      instance-id: microservicecloud-dept8001  #自定义服务名称信息
      prefer-ip-address: true    #访问路径可以显示ip地址

#info
info: 
  app.name: wonders-microservicecloud
  company.name: www.hxj.com
  build.artifactId: $project.artifactId$ #父工程pom文件中配置通过前后缀均为$获取其中src/main/resource/文件夹下数据
  build.version: $project.version$
---
server: 
  port: 8001

spring: 
  profiles: dev
  application: 
    name: microservicecloud-config-dept-client
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02?serverTimezone=UTC
    username: root
    password: 123456

mybatis: 
  mapper-locations: classpath:mybatis/mapper/*.xml  
  type-aliases-package: com.wonders.springcloud.pojo  
  config-location: classpath:mybatis/mybatis.cfg.xml

#客户端注册进eureka服务列表内
eureka:
  client:
    service-url: 
      #defaultZone: http://localhost:6001/eureka
      #入驻多个集群
      defaultZone: http://eureka7001.com:7001/eureka/
  instance: 
      instance-id: microservicecloud-dept8001  #自定义服务名称信息
      prefer-ip-address: true    #访问路径可以显示ip地址

#info
info: 
  app.name: wonders-microservicecloud
  company.name: www.hxj.com
  build.artifactId: $project.artifactId$ #父工程pom文件中配置通过前后缀均为$获取其中src/main/resource/文件夹下数据
  build.version: $project.version$